// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAafwwvANwVQ7i5kSaLdliLBsA09sR3nEs',
    appId: '1:1030662738392:web:22c3c8edaa54bc9162e2ad',
    messagingSenderId: '1030662738392',
    projectId: 'first-app-812ad',
    authDomain: 'first-app-812ad.firebaseapp.com',
    databaseURL: 'https://first-app-812ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-812ad.firebasestorage.app',
    measurementId: 'G-YTXEW9JW0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVdBB8vbwTyxIDEdm7uYGDeJa7EmG3ME',
    appId: '1:1030662738392:android:17ae47c27c53ce8762e2ad',
    messagingSenderId: '1030662738392',
    projectId: 'first-app-812ad',
    databaseURL: 'https://first-app-812ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-812ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZVJL8cTTkimz93I1kmph44KD4tDKeIg',
    appId: '1:1030662738392:ios:f43e69fb91db353b62e2ad',
    messagingSenderId: '1030662738392',
    projectId: 'first-app-812ad',
    databaseURL: 'https://first-app-812ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-812ad.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZVJL8cTTkimz93I1kmph44KD4tDKeIg',
    appId: '1:1030662738392:ios:f43e69fb91db353b62e2ad',
    messagingSenderId: '1030662738392',
    projectId: 'first-app-812ad',
    databaseURL: 'https://first-app-812ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-812ad.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAafwwvANwVQ7i5kSaLdliLBsA09sR3nEs',
    appId: '1:1030662738392:web:cd46dbfa459cbba662e2ad',
    messagingSenderId: '1030662738392',
    projectId: 'first-app-812ad',
    authDomain: 'first-app-812ad.firebaseapp.com',
    databaseURL: 'https://first-app-812ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-812ad.firebasestorage.app',
    measurementId: 'G-MBY74W8ZFW',
  );

}